setwd("D:/Study/Thesis/Experiments/Util/RPlots")
library("ggplot2")
featuresdata = read.csv("ss_04_03_stopwords.csv")
p <- ggplot(featuresdata, aes(x=run, y=f1, group=stopword_options))+ labs(x = "Run Number", y = "F1 score" )
q <- p + geom_point(aes(color=stopword_options, shape=stopword_options), size = 3) + geom_line(aes(color=stopword_options))
q + facet_grid(comb ~ ., scale = "free_y")